[package]
name = "execution-core"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
execution-commitment = { path = "../execution-commitment" }
execution-model = { path = "../execution-model" }
execution-native = { path = "../execution-native" }
execution-serialization = { path = "../execution-serialization" }
execution-trace = { path = "../execution-trace" }
execution-verification = { path = "../execution-verification" }
