"""GENERATED by `python3 -m execution.build` -- do not edit by hand.

An INDEX from program identity to reproducible-build artifacts.
It is NOT the root of trust: every entry names its recipe file,
and `execution.build.verify_build(load_recipe(...), elf_sha256)`
re-derives the artifact identity from source. A verifier who
distrusts this file rebuilds and compares.
"""

GUESTS = {'56a79111f6cbd333204d2f3c8725739b480c30c7c1522438dc1c2d402c6b589a': {'sp1': {'recipe': 'zk/recipes/sp1-pairwise.recipe', 'recipe_identity': '47676d9594c1a3a8b50f345a8fcd6d71a2276f46fa0705dac9a1abda0427bacd', 'elf_sha256': '3100b287c9765aeb3f58c02346e5df57e64ea73a2bc67b71e1cb831866d9a620', 'elf_path': 'zk/artifacts/sp1-pairwise.elf'}, 'nexus': {'recipe': 'zk/recipes/nexus-pairwise.recipe', 'recipe_identity': 'b68f536af60db89547a396c2b1dd089cee66d500e66fd5b7a29148851b7e28ad', 'elf_sha256': 'f70da92f180d906fccec62c0fca9c32fa1a3e69bf263a169402ade908c114f26', 'elf_path': 'zk/artifacts/nexus-pairwise.elf'}}, '68c9233461778c07f752629c7249b11841ed14c76be46621b99dab9e96b18e28': {'sp1': {'recipe': 'zk/recipes/sp1-heat.recipe', 'recipe_identity': '134673ac118fd342cf2ba32cdab64196d92ef7261bc5f38624d81cc9cf1601f8', 'elf_sha256': 'a14e3750da7e221d31842bd6cf983fcc8c0f530b2811537e2a9a9fe803dacf82', 'elf_path': 'zk/artifacts/sp1-heat.elf'}, 'nexus': {'recipe': 'zk/recipes/nexus-heat.recipe', 'recipe_identity': '2245aec927e5a614be662220659d64c80624328b41e43b70489e6dcbebb4aecc', 'elf_sha256': '6b11f85eae24ae04525ac21cb1abe591f2131f0bd6993cf60082c5777eadde33', 'elf_path': 'zk/artifacts/nexus-heat.elf'}}}
