"""GENERATED by `python3 -m execution.build` -- do not edit by hand.

An INDEX from program identity to reproducible-build artifacts.
It is NOT the root of trust: every entry names its recipe file,
and `execution.build.verify_build(load_recipe(...), elf_sha256)`
re-derives the artifact identity from source. A verifier who
distrusts this file rebuilds and compares.
"""

GUESTS = {'56a79111f6cbd333204d2f3c8725739b480c30c7c1522438dc1c2d402c6b589a': {'sp1': {'recipe': 'zk/recipes/sp1-pairwise.recipe', 'recipe_identity': '0225d1d67e0b8acaa5a957eefc5c8c2551dc9169afbd8d6cf813cad79bc40214', 'elf_sha256': '3100b287c9765aeb3f58c02346e5df57e64ea73a2bc67b71e1cb831866d9a620', 'elf_path': 'zk/artifacts/sp1-pairwise.elf'}, 'nexus': {'recipe': 'zk/recipes/nexus-pairwise.recipe', 'recipe_identity': '047e3551b2884f0e9a23d28593de4d8027fdf90a1898b907adb68c17902439c5', 'elf_sha256': '46d92372bde142d3e2d09ff9c032f793ea733464ca9581006747ffe7216decf2', 'elf_path': 'zk/artifacts/nexus-pairwise.elf'}}, '68c9233461778c07f752629c7249b11841ed14c76be46621b99dab9e96b18e28': {'sp1': {'recipe': 'zk/recipes/sp1-heat.recipe', 'recipe_identity': '6e5d1687bcc55243d712553a2b7768b6c587a76418bb48a7a2c44224470d423d', 'elf_sha256': 'a14e3750da7e221d31842bd6cf983fcc8c0f530b2811537e2a9a9fe803dacf82', 'elf_path': 'zk/artifacts/sp1-heat.elf'}, 'nexus': {'recipe': 'zk/recipes/nexus-heat.recipe', 'recipe_identity': '979aafc3e49346c5073d3f24ca08ee4dace604043846d2194ac77ddd9cea8122', 'elf_sha256': '6b11f85eae24ae04525ac21cb1abe591f2131f0bd6993cf60082c5777eadde33', 'elf_path': 'zk/artifacts/nexus-heat.elf'}, 'risc0': {'recipe': 'zk/recipes/risc0-heat.recipe', 'recipe_identity': 'ad2b19287c80a332c135f452fa569daed68cd9c3f20cf9743376477b40034b81', 'elf_sha256': '692c15bda87105c710b667d4656f22e05b5d3574e25da560170bf725a79f04f5', 'elf_path': 'zk/artifacts/risc0-heat.elf'}}}
