"""generate_candidates(specification) -> CandidateSet: the smallest
deterministic transformation from an already-computed
ExperimentSpecification (Phase 35) into a set of generic, descriptive
information-acquisition action candidates -- Phase 36's approved first
stage (Alternative 2) of the future candidates -> feasibility ->
evaluation -> selection pipeline, and ONLY that first stage.

This module answers exactly one question: "what candidate actions could
address these requirements?" It never answers "which is best," "which is
cheapest," "which is feasible," or "which should be selected" -- there is
no cost, feasibility, priority, score, ranking, utility, expected value,
or probability field anywhere in this module, and none is added. See the
module's own tests for the explicit checks that none of those attributes
exist.

Pure function over an already-computed ExperimentSpecification only -- no
EvidencePool, RetrievalEngine, or any earlier-pipeline object at all
(`generate_candidates`'s only argument is the specification layer's own
output), and it never mutates that specification or anything it
references. The specification layer stays completely unaware that a
candidates layer exists: nothing here is ever written back onto
`EvidenceRequirement`/`SpecificationEntry`/`ExperimentSpecification`.

Two closely related but deliberately DIFFERENT identities are computed
here:

  requirement_identity(requirement) -- a content-addressed id for a
  Phase 35 EvidenceRequirement, computed from its existing public fields
  only. Phase 36 explicitly forbade retrofitting an `.id` onto
  EvidenceRequirement itself, so this identity is derived here, by the
  first layer that actually needs it, never by modifying Phase 35.

  ActionCandidate.id -- action_class + the sorted requirement identities
  it targets, exactly the formula Phase 36 sec.L established, computed
  by `make_action_candidate`. Cost/feasibility/priority never
  participate, mirroring every `make_*` factory in `evidence/types.py`
  excluding confidence/timestamp from its own identity.

`action_class` is generated by a small, TOTAL, deterministic RULE over
(role, category) -- never an invented protocol, never a closed ontology
enforced by a Python type. `role` (OBSERVED/PREDICTED/EITHER, from
`materials.specification`) picks which domain the missing information
belongs to; `category` (from `materials.experiment`) picks how much is
already known in that domain. See `_action_class_for`'s own docstring
for the exact reasoning and Phase 37 sec.16's report for the reachability
proof (only 8 of the 18 combinations this function is total over are
ever actually produced by `materials.experiment`'s own category-
assignment logic today).

Composition (Phase 37 sec.7's many-to-many relationship) is exercised in
exactly the one direction the existing data model can justify without
inventing a "these were obtained together" fact it does not establish:
requirements that differ ONLY by which `Criterion` (operator/target)
prompted them -- everything else identical (formulation, property, role,
action_class, criterion CONTEXT, existing evidence, provenance) -- are
merged into one candidate, because a criterion's threshold decides only
whether existing evidence passes; it never decides what would need to be
measured or validated to resolve a conflict or fill a gap. Composition
across different PROPERTIES was deliberately NOT attempted: nothing in
`EvidenceRequirement` records whether two properties were (or could be)
obtained by one shared physical/computational event, and inventing that
association would be exactly the kind of invented procedure Phase 37
sec.8 forbids. See the module's own tests and Phase 37's report for this
as a documented finding, not a silent limitation.
"""

from __future__ import annotations

from dataclasses import dataclass
from types import MappingProxyType
from typing import Dict, Mapping, Set, Tuple

from evidence.identity import content_hash
from evidence.types import Referent
from materials.experiment import (
    INCOMPARABLE_EVIDENCE, MEASUREMENT_WITHOUT_PREDICTION, MISSING_EVIDENCE,
    PREDICTION_WITHOUT_MEASUREMENT,
)
from materials.specification import (
    OBSERVED, PREDICTED, EvidenceRequirement, ExperimentSpecification,
)


def _canonical_context_list(contexts: Tuple[Mapping[str, object], ...]) -> list:
    """A canonical (insertion-order-independent) ordering for a tuple of
    context mappings, for use inside a hashed payload -- sorted by each
    context's own `content_hash`, since dict mappings aren't otherwise
    orderable and `content_hash`'s key-sorted JSON encoding already
    makes each mapping's OWN key order irrelevant."""
    return sorted((dict(c) for c in contexts), key=lambda c: content_hash(c))


def requirement_identity(requirement: EvidenceRequirement) -> str:
    """A deterministic, content-addressed identity for an
    EvidenceRequirement, derived only from its existing public fields --
    Phase 36 forbade retrofitting an `.id` onto EvidenceRequirement, so
    this identity lives here, in the first layer that actually needs it.

    Every field that distinguishes two requirements AS FACTS is
    included: formulation, property, role, gap category, the exact
    criterion being checked (operator + target + context -- two
    requirements differing only by criterion target ARE different
    requirements as facts, even though `_action_group_key` below may
    still decide the same action resolves both), which evidence ids are
    already known, the predicted-side provenance sets, and the
    available/matching comparison contexts. `description` is excluded --
    `materials.specification`'s own docstring already establishes it as
    a convenience field, never canonical; this identity only ever reads
    canonical fields.

    Every id-bearing/context-bearing collection is sorted before
    hashing, so a re-ordering that carries no semantic meaning (e.g.
    which of two conflicting observation ids happens to appear first)
    can never change the identity."""
    payload = {
        "formulation_id": requirement.formulation.id,
        "property": requirement.property,
        "role": requirement.role,
        "category": requirement.category,
        "criterion_operator": requirement.criterion.operator,
        "criterion_target": requirement.criterion.target,
        "criterion_context": dict(requirement.criterion_context),
        "existing_evidence_ids": sorted(requirement.existing_evidence_ids),
        "provenance_observation_id_sets": sorted(
            tuple(sorted(s)) for s in requirement.provenance_observation_id_sets
        ),
        "available_contexts": _canonical_context_list(requirement.available_contexts),
        "matching_contexts": _canonical_context_list(requirement.matching_contexts),
    }
    return content_hash(payload)


def _action_class_for(category: str, role: str) -> str:
    """A total, deterministic RULE over (role, category) -- not a
    lookup table of invented protocols.

    `role` decides which domain the missing information belongs to:
    OBSERVED -> "measurement", PREDICTED -> "model_validation", EITHER
    -> a domain-neutral "acquisition" (used only for MISSING_EVIDENCE,
    where Phase 35 sec.6D already established that preferring one
    domain over the other would invent a preference the evidence does
    not express).

    `category` decides how much is already known in that domain:
    INCOMPARABLE_EVIDENCE means evidence exists but not under a
    matching context -> "context" (obtain evidence under the required
    context, never inventing which context beyond what the criterion
    already states). The three absence categories (MISSING_EVIDENCE,
    MEASUREMENT_WITHOUT_PREDICTION, PREDICTION_WITHOUT_MEASUREMENT)
    mean nothing exists in that domain at all, so there is nothing to
    "repeat" or match a context against -> "unspecified" (this is
    exactly the `measurement:unspecified` example Phase 37 sec.8 itself
    suggested, reached here via PREDICTION_WITHOUT_MEASUREMENT's
    OBSERVED-side requirement, with a symmetric
    `model_validation:unspecified` for MEASUREMENT_WITHOUT_PREDICTION's
    PREDICTED-side requirement). Every other category
    (MEASUREMENT_CONFLICT, MODEL_DISAGREEMENT) means comparable evidence
    already exists and disagrees, so more of the same kind of evidence
    is what is being described -> "repeat".

    This function is total over its full (role, category) domain, but
    only 8 of the 18 combinations it can produce are ever actually
    reachable from `materials.experiment`'s own category-assignment
    logic today (observed never receives MODEL_DISAGREEMENT; EITHER
    never receives anything but MISSING_EVIDENCE) -- see the module's
    own tests for the exhaustive reachability check. Being total over
    the full domain, rather than raising on the unreachable 10, avoids
    this module depending on materials.experiment's internal
    category-assignment logic to know which combinations to special-
    case; it is simpler and equally correct."""
    if role == OBSERVED:
        prefix = "measurement"
    elif role == PREDICTED:
        prefix = "model_validation"
    else:
        prefix = "acquisition"

    if category == INCOMPARABLE_EVIDENCE:
        suffix = "context"
    elif category in (MISSING_EVIDENCE, MEASUREMENT_WITHOUT_PREDICTION, PREDICTION_WITHOUT_MEASUREMENT):
        suffix = "unspecified"
    else:
        suffix = "repeat"

    return f"{prefix}:{suffix}"


def _action_group_key(requirement: EvidenceRequirement, action_class: str) -> tuple:
    """What makes two requirements addressable by literally the SAME
    candidate action -- deliberately NOT the same thing as
    `requirement_identity`. A criterion's operator/target decide only
    whether existing evidence passes or fails; they never decide WHAT
    would need to be measured or validated to resolve a conflict or
    fill a gap, so two requirements differing only by criterion target
    (e.g. the same model disagreement checked against two different
    thresholds) are legitimately satisfied by ONE action and are merged
    here. `criterion_context` is NOT excluded the same way: for
    INCOMPARABLE_EVIDENCE especially, the target context IS what
    determines what needs to be measured (viscosity @ 25C is a
    different action than viscosity @ 30C), so two requirements
    differing only in criterion_context stay separate candidates."""
    return (
        requirement.formulation.id,
        requirement.property,
        requirement.role,
        action_class,
        content_hash(dict(requirement.criterion_context)),
        tuple(sorted(requirement.existing_evidence_ids)),
        tuple(sorted(tuple(sorted(s)) for s in requirement.provenance_observation_id_sets)),
    )


@dataclass(frozen=True)
class ActionCandidate:
    """A generic, descriptive information-acquisition action candidate
    -- Phase 36's abstraction, built here for the first time. Contains
    only what is needed to identify and understand the proposed action;
    no cost/feasibility/priority/score/ranking/utility/expected-value/
    probability/selection field exists here, and none is added -- see
    the module's own tests for the explicit check that none of those
    attributes exist.

    `action_class` is an open string -- never a closed enum, never a
    Python subclass per action kind. Phase 36 and this module's own
    docstring both establish that action classes belong in DATA, not in
    the type hierarchy; `make_action_candidate` places no restriction on
    which strings are valid, so a caller may construct a candidate with
    any `action_class` this module never generates itself.

    `requirement_ids` is the join between this candidate and the
    (possibly more than one) EvidenceRequirements it targets --
    content-hash ids from `requirement_identity`, never a live reference
    back into EvidenceRequirement/ExperimentSpecification objects, and
    never written back onto those objects."""

    id: str
    action_class: str
    requirement_ids: Tuple[str, ...]
    formulation: Referent
    property: str
    role: str
    target_context: Mapping[str, object]
    existing_evidence_ids: Tuple[str, ...]

    def __post_init__(self) -> None:
        object.__setattr__(self, "requirement_ids", tuple(self.requirement_ids))
        object.__setattr__(self, "target_context", MappingProxyType(dict(self.target_context)))
        object.__setattr__(self, "existing_evidence_ids", tuple(self.existing_evidence_ids))
        if not self.action_class:
            raise ValueError("ActionCandidate.action_class must not be empty")
        if not self.requirement_ids:
            raise ValueError("ActionCandidate.requirement_ids must not be empty")


def _candidate_identity(action_class: str, requirement_ids: Tuple[str, ...]) -> str:
    """action_class + the sorted targeted-requirement identity hashes --
    exactly the formula Phase 36 sec.L established. No additional
    distinguishing descriptive field is needed in this generator's
    actual output: `requirement_ids` are themselves content hashes that
    already encode formulation/property/role/category/context/evidence,
    so two candidates sharing both action_class and requirement_ids are
    always the same candidate by construction."""
    return content_hash({"action_class": action_class, "requirement_ids": sorted(requirement_ids)})


def make_action_candidate(
    action_class: str,
    requirement_ids: Tuple[str, ...],
    formulation: Referent,
    property: str,
    role: str,
    target_context: Mapping[str, object],
    existing_evidence_ids: Tuple[str, ...] = (),
) -> ActionCandidate:
    """The only supported way to construct an ActionCandidate -- mirrors
    every `make_*` factory in `evidence/types.py`: id is always derived
    from content, never supplied by the caller."""
    requirement_ids = tuple(sorted(set(requirement_ids)))
    candidate_id = _candidate_identity(action_class, requirement_ids)
    return ActionCandidate(
        id=candidate_id, action_class=action_class, requirement_ids=requirement_ids,
        formulation=formulation, property=property, role=role,
        target_context=target_context, existing_evidence_ids=tuple(sorted(set(existing_evidence_ids))),
    )


@dataclass(frozen=True)
class CandidateSet:
    """The complete, deterministically-ordered result of one
    `generate_candidates` call. `specification` is the unmodified
    ExperimentSpecification this set was generated from -- full
    traceability without duplication, the same pattern
    `ProgramAudit.decision`/`ExperimentGapAnalysis.audit` already use."""

    process_natural_key: str
    specification: ExperimentSpecification
    candidates: Tuple[ActionCandidate, ...]

    def __post_init__(self) -> None:
        object.__setattr__(self, "candidates", tuple(self.candidates))


class _CandidateGroup:
    """Internal, mutable accumulator used only inside
    `generate_candidates` -- never returned, never part of the public
    API. Exists so the two things that must survive requirement merging
    (which requirement ids, which evidence ids) can be built up with a
    plain, deterministically-sortable `set` while the descriptive fields
    that are, by `_action_group_key`'s own construction, guaranteed
    identical across every requirement in the group are recorded once."""

    def __init__(
        self, action_class: str, formulation: Referent, property: str, role: str,
        target_context: Mapping[str, object],
    ) -> None:
        self.action_class = action_class
        self.formulation = formulation
        self.property = property
        self.role = role
        self.target_context = target_context
        self.requirement_ids: Set[str] = set()
        self.existing_evidence_ids: Set[str] = set()


def generate_candidates(specification: ExperimentSpecification) -> CandidateSet:
    """Deterministic, side-effect-free, read-only -- takes only an
    ExperimentSpecification; never calls EvidencePool/RetrievalEngine,
    never mutates `specification` or anything it references, never
    writes a candidate reference back onto any EvidenceRequirement.

    One candidate per distinct `_action_group_key` -- requirements that
    share formulation/property/role/action_class/criterion context/
    evidence/provenance (differing only by criterion operator/target)
    are merged into ONE candidate whose `requirement_ids` names all of
    them (the many-to-many relationship, exercised only in the one
    direction the existing data model can justify -- see the module
    docstring for why cross-property composition was not attempted).

    Output ordering: candidates are returned sorted by their own `id` --
    a canonical, content-derived ordering independent of specification/
    requirement insertion order, dict iteration order, or
    PYTHONHASHSEED. Internal accumulation uses plain dict/set structures
    freely; only this final sort is ever exposed as observable output
    order."""
    groups: Dict[tuple, _CandidateGroup] = {}

    for entry in specification.entries:
        for requirement in entry.requirements:
            action_class = _action_class_for(requirement.category, requirement.role)
            group_key = _action_group_key(requirement, action_class)
            group = groups.get(group_key)
            if group is None:
                group = _CandidateGroup(
                    action_class=action_class, formulation=requirement.formulation,
                    property=requirement.property, role=requirement.role,
                    target_context=requirement.criterion_context,
                )
                groups[group_key] = group
            group.requirement_ids.add(requirement_identity(requirement))
            group.existing_evidence_ids.update(requirement.existing_evidence_ids)

    candidates = tuple(
        make_action_candidate(
            action_class=group.action_class,
            requirement_ids=tuple(group.requirement_ids),
            formulation=group.formulation,
            property=group.property,
            role=group.role,
            target_context=group.target_context,
            existing_evidence_ids=tuple(group.existing_evidence_ids),
        )
        for group in groups.values()
    )
    candidates = tuple(sorted(candidates, key=lambda c: c.id))
    return CandidateSet(
        process_natural_key=specification.process_natural_key,
        specification=specification, candidates=candidates,
    )
